version: "2"
services:
  remonline-tg:
    build: .
    container_name: remonline-tg
    environment:
      # you should specify these variables here or in .env file (see example)
      - TG_TOKEN=${TG_TOKEN}
      - TG_CHAT_IDS=${TG_CHAT_IDS}
      - TG_CHAT_NOTICE_IDS=${TG_CHAT_NOTICE_IDS}
      - API_KEY=${API_KEY}
      - DEBUG=${DEBUG}
